# Copyright 2021 Stenic BV.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sql-operator.fullname" . }}
  labels:
    control-plane: sql-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: sql-operator
  template:
    metadata:
      annotations:
        checksum/admission-webhook.yaml: {{ include (print $.Template.BasePath "/webhook_admission.yaml") . | sha256sum }}
        prometheus.io/scrape: "true"
        {{- if .Values.annotations }}
        {{ toYaml .Values.annotations | nindent 8 }}
        {{- end }}
      labels:
        control-plane: sql-operator
        {{- if .Values.labels }}
        {{ toYaml .Values.labels | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "sql-operator.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.watchNamespaces }}
        - --watch-namespaces={{- include "sql-operator.watchNamespaces" . -}}
        {{- end }}
        - --leader-elect
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{- if .Values.envVars }}
          {{- toYaml .Values.envVars | nindent 10 }}
          {{- end }}
        ports:
          - containerPort: 9443
            name: webhook
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: webhook-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.sidecarContainers }}
      {{ toYaml .Values.sidecarContainers | nindent 6 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      volumes:
      - name: webhook-cert
        secret:
          defaultMode: 420
          secretName: {{ template "sql-operator.fullname" . }}-admission-webhook-keypair
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
